# if set to true then nullability will be determined by the `nullable` property of OpenAPI schema
# if set to false then `required` will be used
# for more info look at https://github.com/surfstudio/SurfGen#nullability
useNewNullableDeterminationStrategy: true

# Will remove listed prefixes from URIs in generated code
prefixesToCutDownInServiceNames:
  - "/api/v1"

templates:

# This option will generate Interface (Protocol) for service

  - type: service
    nameSuffix: Service
    fileExtension: swift
    templatePath: ./Templates/Swift/Service.txt
    destinationPath: ./project/Sources/Services/{name}

# This template will generate Implementation for service

  - type: service
    nameSuffix: Service
    fileExtension: swift
    templatePath: ./Templates/Swift/NetworkService.txt
    destinationPath: ./project/Sources/Services/{name}

# This template will generate Business Model

  - type: model
    nameSuffix: Entity
    fileExtension: swift
    templatePath: ./Templates/Swift/Entity.txt
    destinationPath: ./trash/Sources/Models/{name}

# This template will generate Plain Model (for network communication)

  - type: model
    nameSuffix: Entity
    fileExtension: swift
    templatePath: ./Templates/Swift/Entry.txt
    destinationPath: ./trash/Sources/Models/{name}

# This template will generate alias on other types

  - type: typealias
    fileExtension: swift
    templatePath: ./Templates/Swift/Typealias.txt
    destinationPath: ./trash/Sources/Aliases/{name}

# This template will generate enum

  - type: enum
    fileExtension: swift
    fileNameCase: snakeCase # ATTENTION! Just for example that you can change naming pattern for files
    templatePath: ./Templates/Swift/Entity.txt
    destinationPath: ./trash/Sources/Models/{name}

# We use it to colelct analytics about SurfGen usage inside our company.
# You can set it to gether the sae analytics for ypur company or just delete it from config
analytcsConfig:
    logstashEnpointURI: http://127.0.0.1:6644
    payload:
        project: Test