templates:
  - type: service
    nameSuffix: Service
    fileExtension: swift
    templatePath: ./Templates/v2/Swift/Service.txt
    destinationPath: ./trash/Sources/Services/{name}

  - type: model
    nameSuffix: Entity
    fileExtension: swift
    templatePath: ./Templates/v2/Swift/Entity.txt
    destinationPath: ./trash/Sources/Models/{name}

  - type: enum
    fileExtension: swift
    fileNameCase: snakeCase
    templatePath: ./Templates/v2/Swift/Entity.txt
    destinationPath: ./trash/Sources/Models/{name}

analytcsConfig:
    logstashEnpointURI: http://127.0.0.1:6644
    payload:
        project: Test
