name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release-on-mac:
    name: "Pre Release Fro MacOS"
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test -v
      - name: Make Release Buid
        run: make executable
      - name: Archive
        run: |
          mv Binary surfgen
          zip surfgen_x64.zip surfgen
          zip -r templates.zip Templates

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Development Build"
          files: |
            CHANGLELOG.md
            *.zip