name: "release"

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release-on-mac:
    name: "Release For MacOS"
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test -v
      - name: Make Release Buid
        run: make executable
      - name: Check binary
        run: |
          ./Binary create-config -f swift -t linter
          ./Binary lint -c .surfgen.linter.yaml Tests/Common/RefToAlias/api.yaml
      - name: Archive
        run: |
          mv Binary surfgen
          zip surfgen_macos_x64.zip surfgen
          zip -r templates.zip Templates
          

      - uses: "ncipollo/release-action@v1"
        with:
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: true
          bodyFile: CHANGELOG.md
          allowUpdates: true

  release-on-linux:
    name: "Release For Ubuntu"
    runs-on: ubuntu-latest

    steps:
      - uses: sersoft-gmbh/swifty-linux-action@v1
        with: 
          release-version: 5.3.3
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test -v
      - name: Make Release Buid
        run: make executable
      - name: Check binary
        run: |
          ./Binary create-config -f swift -t linter
          ./Binary lint -c .surfgen.linter.yaml Tests/Common/RefToAlias/api.yaml
      - name: Archive
        run: |
          mv Binary surfgen
          zip surfgen_ubuntu_x64.zip surfgen

      - uses: "ncipollo/release-action@v1"
        with:
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: true
          bodyFile: CHANGELOG.md
          allowUpdates: true