name: Swift

on:
  pull_request:

jobs:
  build_on_mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  build_on_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: sersoft-gmbh/swifty-linux-action@v1
      with: 
        release-version: 5.3.3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
